kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector: # here labels used as a selectors , to attach service to a particular pod.
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
-------

kind: Pod
apiVersion: v1
metadata: 
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
