kind: Service
apiVersion: v1
metadata: 
  name: nodeport
spec:
  type: NodePort
  selector:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: "nodeport"

  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80

---

kind: Pod
apiVersion: v1
metadata:
  name: backend-nodeport
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: "nodeport"
spec:
  containers:
  - name: nginx
    image: nginx