kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-dp
  labels:
    app: frontend
    tier: web
    purpose: deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
      environment: prod
  
  template:
    metadata:
      labels:
        component: backend
        environment: prod
    spec:
      containers:
      - name: node
        image: nginx:latest
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    component: backend
    environment: prod
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
    