kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-dp
  labels:
    app: frontend
    tier: web
    purpose: deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
      environment: prod
  
  template:
    metadata:
      labels:
        component: backend
        environment: prod
    spec:
      containers:
      - name: node
        image: nginx
        ports:
        - containerPort: 80