apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: init-container
    image: nginx
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    # command: ['sh', '-c', "until nslookup googfdfggle.com; do echo waiting for myservice; sleep 2; done"]
    command: ['sh', '-c', "for i in {1..10}; do sleep 10; if nslookup google.com; then exit 0; fi; done; exit 1"]