kind: Pod
apiVersion: v1
metadata:
  name: sa-demo
  namespace: expense
spec:
  serviceAccount: expense-mysql-secret
  initContainers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ['sh', '-c', 'aws secretsmanager get-secret-value --secret-id mysql/expense/secrets --query SecretString --output text > /secrets/.env ']
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  # one pod can contain multiple containers
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    emptyDir: {}