apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    purpose: "toleration-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "user"
    operator: "Equal"
    value: "admin"
    effect: "NoSchedule"
 
    