apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    purpose: "affinity-demo"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: user
            operator: NotIn
            values:
            - admin
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "user"
    operator: "Equal"
    value: "admin"
    effect: "NoSchedule"