
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::344060441143:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-fx5zzaU6LGCt
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::344060441143:user/sivasai
      username: sivasai
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-31T03:51:11Z"
  name: aws-auth
  namespace: kube-system
  uid: bd6c1b25-29ea-4fbd-a9d7-a481c96a2d77
