kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
    purpose: ingress-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      purpose: ingress-demo
  template:
    metadata:
      labels:
        app: app1
        purpose: ingress-demo
    spec:
      containers:
      - name: app1
        image: sivasaikumar943/app1:1.0.0
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: app1
    purpose: ingress-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
